name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
            - name: Install NPM packages
              run: npm install
            - name: Run Prettier
              run: npx prettier --check .

    test-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
            - name: Install NPM packages
              run: npm install
            - name: Execute the tests
              run: npm test
